### ISSUE TITLE
Need device descriptor compose file and what is ffs_dir

### ISSUE THREAD

**Issue by PratikGajera** [kopasiak/simple_usb_chat#1]
1) what usb device descriptor parameter fill in created gadget.

2) I don't know about why below line required so please guide me.

```
       $ mount chat ffs_dr / -t functionfs
```

   and how to created ffs_dir file and what contain it and what is useful for usb gadget.

**Comment by kopasiak** [comment]
probably the best way to create ffs_dir is to simply use mkdir;)

Please watch:

https://fosdem.cu.be/2016/ud2120/make-your-own-usb-device-without-pain-and-money.mp4

As far as I remember I have elaborated there how to use this.

**Comment by PratikGajera** [comment]
I write below line and get the error.

root@beaglebone:/sys/kernel/config/usb_gadget/g1#echo musb-hdrc.0.auto > UDC
-bash: echo: write error: No such device

But i verified the device available in /sys/class/udc directory although this error getting.

**Comment by kopasiak** [comment]
You have to run ffs service before binding gadget to udc

**Comment by PratikGajera** [comment]
working.
Thank you.

**Comment by PratikGajera** [comment]
one more help, i want to make my own usb gadget.But i confused about how to usb device handle control request(transfer) when usb host controller send control request please guide me what API through handle control request.

**Comment by kopasiak** [comment]
When host sends you a control transfer you will get FUNCTIONFS_SETUP event. Then you should check it's type and receive or send the suitable data using read() or write() on ep0

**Comment by PratikGajera** [comment]
Thank you sir.
